name: Catarina Machado
description: Computer Software Engineering Student

markdown: kramdown
highlighter: rouge
paginate: 15
baseurl: 'http://catarinaamachado.github.io/'
domain_name: 'http://catarinaamachado.github.io/'
google_analytics: 'UA-58555211-1'

# Details for the RSS feed generator
url: 'http://catarinaamachado.github.io/'

author:
    name: 'Catarina Machado'
    thumb: '/assets/images/profile.png'
    bio: Computer Software Engineering Student
    url:
      facebook: 'https://www.facebook.com/catarinaamachado'
      linkedin: 'https://www.linkedin.com/in/catarinaamachado/'
      email: 'catarinamachado11@gmail.com'

urls:
    about: /about

img_path: /assets/images/
